<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ValveResourceFormat" Version="20.0.6980" />
    <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
  </ItemGroup>
</Project>
